[env]
# Forces RocksDB to use the system library if available
ROCKSDB_LIB_DIR = "/usr/local/lib"

[build]
rustc-wrapper = "sccache"

[profile.dev]
incremental = false

[profile.release]
incremental = false
